import { useQuery, gql } from "@apollo/client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-20 px-0 flex flex-col justify-center items-center flex-1">
        <ExchangeRates />
      </main>
    </>
  );
}

interface ExchangeRate {
  currency: string;
  rate: number;
}
interface ExchangeRatesData {
  rates: ExchangeRate[];
}

function ExchangeRates() {
  const { loading, error, data } = useQuery<ExchangeRatesData>(EXCHANGE_RATES);

  if (loading) return <p>Loading...</p>;
  if (error || data === undefined) return <p>Error :(</p>;

  return (
    <>
      {data.rates.map(({ currency, rate }) => (
        <div key={currency}>
          <p>
            {currency}: {rate}
          </p>
        </div>
      ))}
    </>
  );
}

const EXCHANGE_RATES = gql`
  query GetExchangeRates {
    rates(currency: "USD") {
      currency
      rate
    }
  }
`;
